# Generated by Django 5.1.2 on 2024-11-05 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_category_options_listing_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.CreateModel(
            name='ListingCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
            options={
                'verbose_name': 'Listing Category',
                'verbose_name_plural': 'Listing Categories',
                'unique_together': {('category', 'listing')},
            },
        ),
    ]
