# Generated by Django 5.1.2 on 2024-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_create_date_listing_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
