# Generated by Django 5.1.2 on 2024-11-11 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_win_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
